### ISSUE TITLE
Boom missing in 2.1.8

### ISSUE THREAD

**Issue by master-elodin** [Medium/phantomjs#578]
When trying to install with 2.1.8, I get the following error. 2.1.7 works fine.

```
> phantomjs-prebuilt@2.1.8 install /root/workspace/node_modules/phantomjs-prebuilt
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/workspace/common-ui-all/node_modules/request/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by nicks** [comment]
that error doesn't look like it's related to this package? it looks like it's coming from root/workspace/common-ui-all/node_modules/request/node_modules/hawk/lib/index.js

**Comment by master-elodin** [comment]
Did the version of hawk get upgraded in 2.1.8? I noticed the version
increased 15 hours ago.

I had ^2.1.7 in my package.json. That worked yesterday and when I remove
the ^ it works with 2.1.7.

**Comment by nicks** [comment]
try wiping out your node_modules directory and re-installing everything. My guess is that you're using an older version of NPM and it put your dependency tree in a weird state

**Comment by anthonyettinger** [comment]
This is happening on jenkins, so there is no stale `./node_modules` folder

**Comment by rmg** [comment]
Seems to be ok when npm@3 is used, but not when npm@2 is used as shipped with node 0.10, 0.12, and 4.x.

**Comment by rmg** [comment]
@master-elodin same problem as #580 if you want to follow the thread there.
