### ISSUE TITLE
Fresh npm install failing in Mac OS / Ubuntu

### ISSUE THREAD

**Issue by zeagord** [Medium/phantomjs#607]
It was working fine until recently. Tried with different versions between 2.1.6 - 2.1.2. 

Node Version - v5.9.1
npm Version - 3.7.3

```
> phantomjs-prebuilt@2.1.12 install /Users/****/****/****/***/node_modules/phantomjs-prebuilt
> node install.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/rg3/Documents/code/UI/cuckoo-docker/cuckoo/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by NicolasPelletier** [comment]
I get the same type of errors:
```
> phantomjs-prebuilt@2.1.12 install /Users/pelletn/lagoa_src/LynxDeploy/work/0.0.1/LynxUtils/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module './writer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pelletn/lagoa_src/LynxDeploy/work/0.0.1/LynxUtils/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/asn1/lib/ber/index.js:7:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

node 4.4.7
npm 2.15..8

Mac OSX 10.11.6

**Comment by NicolasPelletier** [comment]
Seems similar to #606...

**Comment by NicolasPelletier** [comment]
This is the same problem as #580, #578, #553 and my own #584.

This was solved by 84438f5c5a6c55d297298df03dc2449ebc156950 so I bet that it was broken by the removal of the bundle dependencies in 076b9595c3b8a5c700ebf8ebc3c1a324974e1ea4.

**Comment by ourmaninamsterdam** [comment]
```
> phantomjs-prebuilt@2.1.14 install **/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs-prebuilt
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (**/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
 
> hiredis@0.5.0 install **/node_modules/node-request-caching/node_modules/hiredis
> node-gyp rebuild
```

node 4.7.3
npm 2.15.11

Linux 4.4.47-boot2docker

**Comment by zeagord** [comment]
Closing this issue as I don't see this problem anymore and it is quite old.
